version: "3"
services:
  node:
    build:
      context: ./node
      dockerfile: node.dockerfile
    volumes:
    - ./node:/node
  golang:
    build:
      context: ./golang
      dockerfile: golang.dockerfile
    volumes:
    - ./golang:/go
  git:
    build:
      context: ./git
      dockerfile: git.dockerfile
    volumes:
    - .:/workspace
